name: 'company_atlas'
version: '1.0.0'
config-version: 2

profile: 'company_atlas'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  company_atlas:
    raw:
      +materialized: table
      +schema: raw
    bronze:
      +materialized: view
      +schema: bronze
    marts:
      +materialized: table
      +schema: marts
      unified_companies:
        +materialized: table

vars:
  source_database: COMPANY_ATLAS
  source_schema: RAW

