company_atlas:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', '') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: COMPANY_ATLAS
      # Default schema (models use explicit schemas from dbt_project.yml: raw, bronze, marts)
      # Custom generate_schema_name macro ensures no prefix is added
      schema: raw
      role: "{{ env_var('SNOWFLAKE_ROLE', 'TRANSFORM') }}"
      threads: 4
      query_tag: "dbt_company_atlas"
