-- Drop old schemas in Snowflake
-- This script removes all DEV_* and ANALYTICS_* prefixed schemas
-- Keeps: RAW, STAGING, BRONZE, MARTS, PUBLIC, INFORMATION_SCHEMA
-- Run this as a user with appropriate privileges (e.g., ACCOUNTADMIN or schema owner)
-- Note: CASCADE will drop all objects (tables, views, etc.) within the schemas

USE DATABASE COMPANY_ATLAS;
USE ROLE ACCOUNTADMIN;  -- Or use the role that owns these schemas

-- Drop DEV_* prefixed schemas
DROP SCHEMA IF EXISTS COMPANY_ATLAS.DEV_BRONZE CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.DEV_MARTS CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.DEV_RAW CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.DEV_STAGING CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.DEV CASCADE;

-- Drop ANALYTICS_* prefixed schemas
DROP SCHEMA IF EXISTS COMPANY_ATLAS.ANALYTICS_BRONZE CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.ANALYTICS_MARTS CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.ANALYTICS_RAW CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.ANALYTICS_STAGING CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS.ANALYTICS CASCADE;

-- Drop case variations if they exist
DROP SCHEMA IF EXISTS COMPANY_ATLAS."Dev" CASCADE;
DROP SCHEMA IF EXISTS COMPANY_ATLAS."analytics" CASCADE;

-- Verify schemas are dropped
-- Should only show: RAW, STAGING, BRONZE, MARTS, PUBLIC, INFORMATION_SCHEMA
SHOW SCHEMAS IN DATABASE COMPANY_ATLAS;

